// <auto-generated />
namespace CoolApp.Infraestructure.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NewFriendship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewFriendship));
        
        string IMigrationMetadata.Id
        {
            get { return "201307042322148_NewFriendship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
